("use client");
import Head from "next/head";
import { Fragment } from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Interactive wall</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Fragment>
        <div className="container">
          <h1>Home page</h1>
          <h2>Second Element</h2>
        </div>
      </Fragment>
    </>
  );
}
